# Generated by Django 4.0.1 on 2024-07-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0008_pincomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pinterest.pincomment', verbose_name='Parent Comment'),
        ),
    ]
